name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  tests:
    runs-on: self-hosted
    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1]
        wordpress: [^5.0, ^6.0]
        exclude:
          - php: 7.4
            wordpress: ^4.0

    name: PHP ${{ matrix.php }} - Wordpress ${{ matrix.wordpress }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{secrets.DEPLOY_TOKEN}}
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress
      - name: Execute tests
        run: vendor/bin/phpunit --verbose